[package]
name = "pyunilogs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyunilogs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
macos-unifiedlogs = {git = "https://github.com/mandiant/macos-UnifiedLogs", branch="main"}

simplelog = "0.12.0"
serde_json = "1.0.79"
log = "0.4.14"
clap = {version = "3.2.22", features = ["derive"]}
