[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "maldives"
version = "0.0.7"
authors = [
  { name="To Chin Yu", email="ytc@alum.mit.edu" },
]
description = "Tools for systematic commodities analysis."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'pandas',
  'scikit-learn',
  'fredapi',
  'wallstreet',
  'scipy',
  'plotly',
  'findiff',
  'matplotlib'
]

[project.urls]
Homepage = "https://github.com/ytcs/maldives"
Issues = "https://github.com/ytcs/maldives/issues"