[tool.poetry]
name = "python-spartan"
version = "0.1.8"
description = "Spartan, often referred to as \"The swiss army knife for serverless development,\" is a tool that simplifies the creation of serverless applications on popular cloud providers by generating Python code for classes and more. It streamlines your development process, saving you time and ensuring code consistency in your serverless projects."
authors = ["nerdmonkey <sydel.palinlin@gmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.9.0"}
black = "^23.9.1"
isort = "^5.12.0"
pytest = "^7.4.2"
flake8 = "^6.1.0"
requests = "^2.31.0"
alembic = "^1.12.0"
poetry = "^1.7.0"
pytest-cov = "^4.1.0"
pyyaml = "^6.0.1"
pymysql = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
spartan = "python_spartan.main:app"
