[tool.poetry]
name = "func3lib"
version = "0.0.6"
description = "Three functions func3lib: 'transpose2d', 'window1d' and 'convolution2d'."
authors = ["LinasTamk <linastamk@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "func3lib"}]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
