[project]
name = "sdlib"
version = "0.0.1"
authors = [
    { name="ljleb" },
]
description = "Stable Diffusion Library"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
