[build-system]
requires = [
    "setuptools>=54",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "auto-tmux"
version = "0.2.2"
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}
# author = "Calacuda"
description = "yet another tmux automation script that takes yaml"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",  
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
    ]
dependencies = [
    "tqdm",
    "pyaml",
    "libtmux"
]

[project.scripts]
auto-tmux = "auto_tmux:run_cli"
