[filters.abs]
fn = "builtins.abs"  # "jinja2.filters.abs"
group = "builtin"
[filters.abs.examples.basic]
template = """
{{ -5 | abs }}
"""

[filters.attr]
fn = "jinja2.filters.do_attr"
group = "builtin"
[filters.attr.examples.basic]
template = """
{{ "abc" | attr("removesuffix") }}
"""

[filters.batch]
fn = "jinja2.filters.do_batch"
group = "builtin"
[filters.batch.examples.basic]
template = """
{{ ["a", "b", "c", "d", "e"] | batch(2) }}
"""

[filters.capitalize]
fn = "jinja2.filters.do_capitalize"
group = "builtin"
[filters.capitalize.examples.basic]
template = """
{{ "abc" | capitalize }}
"""

[filters.center]
fn = "jinja2.filters.do_center"
group = "builtin"
[filters.center.examples.basic]
template = """
{{ "sth" | center(20) }}
"""

[filters.default]
fn = "jinja2.filters.do_default"
group = "builtin"
aliases = ["d"]
[filters.default.examples.basic]
template = """
{{ variable | default("some fallback") }}
"""

[filters.dictsort]
fn = "jinja2.filters.do_dictsort"
group = "builtin"
[filters.dictsort.examples.basic]
template = """
{{ {"b": 1, "a": 2} | dictsort }}
"""

[filters.escape]
fn = "jinjarope.textfilters.escape"
group = "builtin"
aliases = ["e"]
[filters.escape.examples.basic]
template = """
{{ "<[]>" | escape }}
"""

[filters.filesizeformat]
fn = "jinja2.filters.do_filesizeformat"
group = "builtin"
[filters.filesizeformat.examples.basic]
template = """
{{ 134324324234 | filesizeformat }}
"""

[filters.first]
fn = "jinja2.filters.do_first"
group = "builtin"
[filters.first.examples.basic]
template = """
{{ [1, 2, 3] | first }}
"""

[filters.float]
fn = "jinja2.filters.do_float"
group = "builtin"
[filters.float.examples.basic]
template = """
{{ "0.4" | float }}
"""

[filters.forceescape]
fn = "jinja2.filters.do_forceescape"
group = "builtin"
[filters.forceescape.examples.basic]
template = """
{{ "<>" | forceescape }}
"""

[filters.format]
fn = "jinja2.filters.do_format"
group = "builtin"
[filters.format.examples.basic]
template = """
{{ "{test}" | format(test="abc") }}
"""

[filters.groupby]
fn = "jinja2.filters.do_groupby"
group = "builtin"
[filters.groupby.examples.basic]
template = """
{{ [cycler] | groupby("__module__") }}
"""

[filters.indent]
fn = "jinja2.filters.do_indent"
group = "builtin"
[filters.indent.examples.basic]
template = """
{{ "abc\fdef" | indent }}
"""

[filters.int]
fn = "jinja2.filters.do_int"
group = "builtin"
[filters.int.examples.basic]
template = """
{{ "3" | int }}
"""

[filters.join]
fn = "jinja2.filters.do_join"
group = "builtin"
[filters.join.examples.basic]
template = """
{{ ["a", "b", "c"] | join }}
"""

[filters.last]
fn = "jinja2.filters.do_last"
group = "builtin"
[filters.last.examples.basic]
template = """
{{ ["a", "b", "c"] | last }}
"""

[filters.length]
fn = "builtins.len"  # "jinja2.filters.len"
group = "builtin"
aliases = ["count"]
[filters.length.examples.basic]
template = """
{{ ["a", "b", "c"] | length }}
"""

[filters.list]
fn = "jinja2.filters.do_list"
group = "builtin"
[filters.list.examples.basic]
template = """
{{ ("a", "b") | list }}
"""

[filters.lower]
fn = "jinja2.filters.do_lower"
group = "builtin"
[filters.lower.examples.basic]
template = """
{{ "ABC" | lower }}
"""

[filters.items]
fn = "jinja2.filters.do_items"
group = "builtin"
[filters.items.examples.basic]
template = """
{{ {"a": "b"} | items }}
"""

[filters.map]
fn = "jinja2.filters.do_map"
group = "builtin"
[filters.map.examples.basic]
template = """
{{ [1, cycler] | map(attribute="__doc__") }}
"""

[filters.min]
fn = "jinja2.filters.do_min"
group = "builtin"
[filters.min.examples.basic]
template = """
{{ [1, 2, 3] | min }}
"""

[filters.max]
fn = "jinja2.filters.do_max"
group = "builtin"
[filters.max.examples.basic]
template = """
{{ [1, 2, 3] | max }}
"""

[filters.pprint]
fn = "jinja2.filters.do_pprint"
group = "builtin"
[filters.pprint.examples.basic]
template = """
{{ ([10000] * 10) | pprint }}
"""

[filters.random]
fn = "jinja2.filters.do_random"
group = "builtin"
[filters.random.examples.basic]
template = """
{{ [1, 2, 3] | random }}
"""

# [filters.reject]
# fn = "jinja2.filters.do_reject"
# group = "builtin"
# [filters.reject.examples.basic]
# template = """
# {{ "sth" | reject }}
# """

# [filters.rejectattr]
# fn = "jinja2.filters.do_rejectattr"
# group = "builtin"
# [filters.rejectattr.examples.basic]
# template = """
# {{ "sth" | rejectattr }}
# """

[filters.replace]
fn = "jinja2.filters.do_replace"
group = "builtin"
[filters.replace.examples.basic]
template = """
{{ "abc" | replace("a", "x") }}
"""

[filters.reverse]
fn = "jinja2.filters.do_reverse"
group = "builtin"
[filters.reverse.examples.basic]
template = """
{{ [1, 2, 3] | reverse }}
"""

[filters.round]
fn = "jinja2.filters.do_round"
group = "builtin"
[filters.round.examples.basic]
template = """
{{ 1.6 | round }}
"""

[filters.safe]
fn = "jinja2.filters.do_mark_safe"
group = "builtin"
[filters.safe.examples.basic]
template = """
{{ "abc" | safe }}
"""

# [filters.select]
# fn = "jinja2.filters.do_select"
# group = "builtin"
# [filters.select.examples.basic]
# template = """
# {{ "sth" | select }}
# """

# [filters.selectattr]
# fn = "jinja2.filters.do_selectattr"
# group = "builtin"
# [filters.selectattr.examples.basic]
# template = """
# {{ "sth" | selectattr }}
# """

# [filters.slice]
# fn = "jinja2.filters.do_slice"
# group = "builtin"
# [filters.slice.examples.basic]
# template = """
# {{ "sth" | slice }}
# """

[filters.sort]
fn = "jinja2.filters.do_sort"
group = "builtin"
[filters.sort.examples.basic]
template = """
{{ ["c", "b", "a"] | sort }}
"""

# [filters.string]
# fn = "jinja2.filters.soft_str"
# group = "builtin"
# [filters.string.examples.basic]
# template = """
# {{ "abc" | string }}
# """

[filters.striptags]
fn = "jinja2.filters.do_striptags"
group = "builtin"
[filters.striptags.examples.basic]
template = """
{{ "<p>text</p>" | striptags }}
"""

[filters.sum]
fn = "jinja2.filters.do_sum"
group = "builtin"
[filters.sum.examples.basic]
template = """
{{ [1, 2, 3] | sum }}
"""

[filters.title]
fn = "jinja2.filters.do_title"
group = "builtin"
[filters.title.examples.basic]
template = """
{{ "abc" | title }}
"""

[filters.trim]
fn = "jinja2.filters.do_trim"
group = "builtin"
[filters.trim.examples.basic]
template = """
{{ "  abc  " | trim }}
"""

# [filters.truncate]
# fn = "jinja2.filters.do_truncate"
# group = "builtin"
# [filters.truncate.examples.basic]
# template = """
# {{ "sth" | truncate }}
# """

[filters.unique]
fn = "jinja2.filters.do_unique"
group = "builtin"
[filters.unique.examples.basic]
template = """
{{ [1, 2, 1] | unique }}
"""

[filters.upper]
fn = "jinja2.filters.do_upper"
group = "builtin"
[filters.upper.examples.basic]
template = """
{{ "sth" | upper }}
"""

[filters.urlencode]
fn = "jinja2.filters.do_urlencode"
group = "builtin"
[filters.urlencode.examples.basic]
template = """
{{ "Some text" | urlencode }}
"""

[filters.urlize]
fn = "jinja2.filters.do_urlize"
group = "builtin"
[filters.urlize.examples.basic]
template = """
{{ "some text" | urlize }}
"""

[filters.wordcount]
fn = "jinja2.filters.do_wordcount"
group = "builtin"
[filters.wordcount.examples.basic]
template = """
{{ "Some longer text" | wordcount }}
"""

[filters.wordwrap]
fn = "jinja2.filters.do_wordwrap"
group = "builtin"
[filters.wordwrap.examples.basic]
template = """
{{ "sth" | wordwrap }}
"""

# [filters.xmlattr]
# fn = "jinja2.filters.do_xmlattr"
# group = "builtin"
# [filters.xmlattr.examples.basic]
# template = """
# {{ "sth" | xmlattr }}
# """

[filters.tojson]
fn = "jinja2.filters.do_tojson"
group = "builtin"
[filters.tojson.examples.basic]
template = """
{{ "[1, 2]" | tojson }}
"""

