[project]
name = "pythonBLEperipheral"
version = "0.0.3"
authors = [
	{name="Christoph Willing", email="chris.willing@linux.com"},
	{name="Douglas Otwell", email="Douglas6@github.com"},
]
description = "Library supporting BLE peripheral applications"
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/chris.willing/python-ble-peripheral"
"Bug Tracker" = "https://gitlab.com/chris.willing/python-ble-peripheral/issues"


[build-system]
requires = ["setuptools>61.0"]
build-backend = "setuptools.build_meta"
