[tool.poetry]
name = "aws-org-client"
version = "0.0.14"
description = "Browse and manage AWS identity and organization resources."
authors = ["Sam Holden <sam.holden@digital.cabinet-office.gov.uk>"]
readme = "README.md"
repository = "https://github.com/hackersandslackers/python-poetry-tutorial/"
documentation = "https://hackersandslackers.com/python-poetry/"
keywords = [
    "AWS",
    "Identity Store",
    "Organizations",
    "SSO"
]


[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.28.66"
typing-extensions = "^4.8.0"



[tool.poetry.group.dev.dependencies]
coverage = "^7.3.2"
pylint = "^3.0.2"
black = "^23.10.1"
bandit = "^1.7.5"
pytest = "^7.4.2"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^1.3.0"
moto = "^4.2.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
