[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hulk-ultimate-python"
version = "0.0.5"
authors = [
    { name = "JHercules", email = "JHercules_qz@qq.com" },
]
description = "Hulk Library for Python."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/JHerculesqz/Hulk"
Issues = "https://github.com/JHerculesqz/Hulk/issues"
