[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "EnglishAssistantForm"
version = "1.0.0"
authors = [
  { name="Seyed Mousa Sajadi(WinCento)", email="sajadimousa@gmail.com" },
]
description = "To help improve learning a language"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yasharsajadi/EnglishAssistantForm"