[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'pysocketsio'
version = '1.7.4'
description = 'This module provides a wrapper for the built-in socket module in python. The program provides server and. client classes, with the communication methods.'
classifiers = [
	'Intended Audience :: Developers',
	'License :: OSI Approved :: MIT License',
	'Programming Language :: Python',
	'Programming Language :: Python :: 3.10',
	'Programming Language :: Python :: 3.11',
	'Operating System :: OS Independent'
]
dynamic = ["dependencies", "optional-dependencies"]
