[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spectronator"
version = "0.0.1"
authors = [
  { name="Joni Kemppainen", email="joni.kemppainen@windowslive.com" },
]
description = "A spectral sensitivity analyser for time series data"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
  "scipy",
  "matplotlib",
  "tk_steroids",
  "python-biosystfiles",
]

[project.urls]
Homepage = "https://github.com/jkemppainen/spectronator"
Issues = "https://github.com/jkemppainen/spectronator/issues"
