[tool.poetry]
name = "prosper-shared"
version = "0.1.9"
description = ""
authors = ["Graham Tibbitts <graham.tibbitts@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
autohooks = "^23.10.0"
autohooks-plugin-black = "^23.10.0"
autohooks-plugin-pytest = "^23.10.0"
autohooks-plugin-isort = "^23.10.0"
autohooks-plugin-ruff = "^23.11.0"
autoimport = "^1.3.3"
mdformat-gfm = "^0.3.5"
mutmut = "^2.4.4"
pydocstyle = "^6.3.0"
pydoclint = "^0.3.8"
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"
pytest-sugar = "^0.9.7"
toml-sort = "^0.23.1"
tox = "^4.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autohooks]
mode = "poetry"
pre-commit = [
    "prosper_shared.autohooks.autoimport",
    "autohooks.plugins.black",
    "autohooks.plugins.ruff",
    "autohooks.plugins.isort",
    "prosper_shared.autohooks.tomlsort",
    "prosper_shared.autohooks.mdformat",
    "prosper_shared.autohooks.dynamic_versioning",
]


[tool.poetry-dynamic-versioning]
enable = false
metadata = false
style = "semver"
vcs = "git"
bump = true

[tool.autohooks.plugins.ruff]
arguments = '--fix'

[tool.isort]
profile = "black"

[tool.ruff.lint]
extend-ignore = ["E501"]
fixable = ["ALL"]
unfixable = []

[tool.tomlsort]
trailing_comma_inline_array = true
spaces_indent_inline_array = 4
sort_first = ["tool.poetry"]
