[project]
name = "oarepo-tools"
version = "0.1.5"
description = "OARepo tools"
readme = "README.md"
authors = [
  {name = "Miroslav Simek", email = "miroslav.simek@cesnet.cz" }
]
dependencies = [
  "click",
  "polib",
  "jinja2",
  "babel",
  "PyYAML"
]

[project.scripts]
make-translations = "oarepo_tools.make_translations:main"

[tool.setuptools]
# ...
# By default, include-package-data is true in pyproject.toml, so you do
# NOT have to specify this line.
include-package-data = true


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
