[project]
name = "python-logvista"
version = "0.1.2"
description = "LogVista SDK for Python"
authors = [{name = "Dencyuman", email = "t.tanaka@triggerhack.com"}]
license = { file = "LICENSE" }
readme = "README.md"

[build-system]
requires = ["setuptools", "wheel"]

[options]
install_requires = [
    "requests",
    "httplib2",
    "msgpack",
    "psutil",
]

[options.extras_require]
dev = [
    "pytest"
]
