[project]
name = "ai_emotion"
version = "0.3.1"
description = "Representation of emotional state for use in AI agents."
authors = [
    { name = "Matt Zhang", email = "set.stun@gmail.com" },
]
dependencies = [
    "py-gpt-interface>=0.3.2",
    "pandas>=2.0.3",
    "numpy>=1.24.4",
    "rich>=13.7.0",
]
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool]
