[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "patcherex"
version = "2.0.1"
readme = "README.md"
dependencies = [
    "angr",
    "pyelftools",
    "lief",
    "keystone-engine",
    "intelhex",
    "requests",
]

[project.optional-dependencies]
Test = [
    "shellphish-qemu",
]

[tool.setuptools.packages]
find = {}
