[tool.poetry]
name = "compare_datasets_pure_python"
version = "0.0.1"
description = "The library that compares two dataframes"
authors = ["Kumar Shantanu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.8"
polars = "^0.19.5"
tabulate = "^0.8.9"
jinja2 = "^3.1.2"
pandas = "^2.1.3"
tqdm = "^4.66.1"
Levenshtein = "^0.23.0"
scipy = "^1.11.4"





[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

