[package]
name = "serdesripy"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "serdesripy"
crate-type = ["cdylib"]

[dependencies]
arrow = { git = "https://github.com/apache/arrow-rs", rev="fbbb61d94282165f9bb9f73fb4d00a3af16d4aee", features = ["pyarrow"] }
# arrow = { version = "48.0.0", features = ["pyarrow"] }
serde_esri = { git = "https://github.com/josiahparry/serde_esri", features = ["geoarrow"]}
pyo3 = "0.20.0"
serde_json = "1.0.108"
